#!/bin/bash

clear

rm bin/compiled

python3 preprocessor.py "bootloader.asm" src/bootloader

cd bin

nasm -f elf64 output.asm -o asm.ob

nasm -f elf64 ./../src/bootloader/shared_data.asm -o asm.o

gcc -c -g -Wall -m64 ../src/**/*.c -I ../src/global_includes/ -I ../src/kernel/ -I ../src/kernel/memory/ -I ../src/drivers/ -mcmodel=large -nostdlib -ffreestanding -mno-red-zone -fno-exceptions -nodefaultlibs -fno-builtin -fno-pic && touch compiled

ld -m elf_x86_64 -static -nostdlib -T ../bootloader_linker.ld asm.ob -o bootloader.img

ld -m elf_x86_64 -static -nostdlib -T ../kernel_linker.ld *.o -o kernel.img+

truncate -s 1K bootloader.img
asm/rwonce.h
cat bootloader.img > os.img
cat kernel.img >> os.img


rm asm.ob
mv font.o font.o.preserve
rm *.o
mv font.o.preserve font.o

#mkisofs -no-emul-boot -input-charset utf-8 -boot-load-size 10 -exclude-list ../exclude.txt -o os.iso -b os.img .

truncate -s 1M os.img

echo compiled

cd ..

