#!/bin/bash

if [ -e bin/compiled ]
then
    rm -f memdump
    qemu-system-x86_64 -smp cpus=2 -cpu max \
        -device ahci,id=ahci \
        -device ide-hd,drive=disk,bus=ahci.0\
        -drive file=bin/os.img,format=raw \
        -drive file=bin/disk.img,id=disk,if=none,format=raw \
        -m 4G \
        -debugcon file:/dev/stdout -monitor stdio \
        -D bin/qemu_log.txt -d int \
        -no-reboot -no-shutdown
else
    echo "compiler errors!"
fi
